name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Ansible version
        run: |
          ansible --version

      - name: Test connection to WordPress server
        run: |
          ansible wordpress \
            -i ansible-wordpress/inventory \
            -m ping

      - name: Validate Ansible playbook
        run: |
          ansible-playbook \
            -i ansible-wordpress/inventory \
            ansible-wordpress/wordpress.yml \
            --syntax-check

      - name: Deploy WordPress
        run: |
          ansible-playbook \
            -i ansible-wordpress/inventory \
            ansible-wordpress/wordpress.yml